version: '3.8'

services:
  api_gateway:
    build:
      context: ../gateway/api_gateway
    container_name: api_gateway
    ports:
      - "3000:3000"
    environment:
      - AI_SERVICE_URL=http://ai_service:8000
      - DOC_SERVICE_URL=http://document_service:4000
    depends_on:
      - ai_service
      - document_service
    volumes:
      # Mount the docs folder so the Swagger UI can find the contract JSON
      - ../docs:/usr/src/app/docs
    networks:
      - ringisho-net

  ai_service:
    build:
      context: ../services/ai_service
    container_name: ai_service
    ports:
      - "8000:8000"
    env_file:
      - ../services/ai_service/.env
    networks:
      - ringisho-net

  document_service:
    build:
      context: ../services/document_service
    container_name: document_service
    ports:
      - "4000:4000"
    environment:
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=password
    depends_on:
      - minio
    networks:
      - ringisho-net

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000" # S3 API endpoint
      - "9001:9001" # MinIO Console Browser UI
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    volumes:
      - ../minio-data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
    networks:
      - ringisho-net

networks:
  ringisho-net:
    driver: bridge
